# Generated by Django 4.1.5 on 2023-01-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailroom',
            options={'verbose_name': ' جزییات اتاق', 'verbose_name_plural': 'جزییات اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق ها'},
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='is_Reservation',
            field=models.BooleanField(default=False, null=True, verbose_name='رزرو شده/ نشده'),
        ),
    ]
