# Generated by Django 4.1.5 on 2023-01-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_detailroom_options_alter_hotelroom_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailroom',
            name='Possibilities',
        ),
        migrations.AlterField(
            model_name='detailroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/room', verbose_name='عکس'),
        ),
    ]
