# Generated by Django 4.1.5 on 2023-01-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_remove_detailroom_possibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='عکس'),
        ),
    ]
