# Generated by Django 4.1.5 on 2023-01-23 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_module', '0005_remove_hotelroom_date_in_remove_hotelroom_date_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailroom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص رزرو کرده'),
        ),
    ]
