# Generated by Django 4.1.5 on 2023-01-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0006_detailroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='is_Reservation',
        ),
        migrations.AddField(
            model_name='detailroom',
            name='is_Reservation',
            field=models.BooleanField(default=False, null=True, verbose_name='رزرو شده/ نشده'),
        ),
    ]
