# Generated by Django 4.1.5 on 2023-01-23 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_module', '0007_remove_hotelroom_is_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailroom',
            name='is_Reservation',
        ),
        migrations.RemoveField(
            model_name='detailroom',
            name='user',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='is_Reservation',
            field=models.BooleanField(default=False, null=True, verbose_name='رزرو شده/ نشده'),
        ),
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.hotelroom', verbose_name='اتاق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
        ),
    ]
