# Generated by Django 4.1.5 on 2023-01-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0008_remove_detailroom_is_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserved',
            name='date_in',
            field=models.DateField(null=True, verbose_name='تاریخ ورود'),
        ),
        migrations.AddField(
            model_name='reserved',
            name='date_out',
            field=models.DateField(null=True, verbose_name='تاریخ خروج'),
        ),
    ]
