# Generated by Django 4.1.5 on 2023-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0009_reserved_date_in_reserved_date_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserved',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='reserved',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='استان'),
        ),
    ]
