# Generated by Django 4.1.5 on 2023-01-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0010_reserved_city_reserved_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved',
            name='city',
        ),
        migrations.RemoveField(
            model_name='reserved',
            name='state',
        ),
    ]
