# Generated by Django 4.1.5 on 2023-01-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_module', '0011_remove_reserved_city_remove_reserved_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='is_Reservation',
        ),
        migrations.AddField(
            model_name='reserved',
            name='is_Reservation',
            field=models.BooleanField(null=True, verbose_name='رزرو شده/ نشده'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='home_module.detailroom', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL, verbose_name='شخص'),
        ),
    ]
