# Generated by Django 4.1.5 on 2023-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0012_remove_hotelroom_is_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='is_Reservation',
            field=models.CharField(max_length=200, null=True, verbose_name='رزرو شده/ نشده'),
        ),
    ]
