# Generated by Django 4.1.5 on 2023-01-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0013_alter_reserved_is_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='is_Reservation',
            field=models.BooleanField(null=True, verbose_name='رزرو شده/ نشده'),
        ),
    ]
