# Generated by Django 4.1.5 on 2023-01-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0015_hotelroom_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='Reservation',
        ),
    ]
