# Generated by Django 4.1.5 on 2023-01-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0018_remove_detailroom_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailroom',
            name='number',
        ),
    ]
