# Generated by Django 4.1.5 on 2023-01-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0022_reserved_aa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved',
            name='aa',
        ),
    ]
