# Generated by Django 4.1.5 on 2023-01-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0023_remove_reserved_aa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailroom',
            name='Reservation',
            field=models.BooleanField(null=True, verbose_name='رزرو شده/ نشده'),
        ),
    ]
