# Generated by Django 4.1.5 on 2023-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0024_detailroom_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailroom',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ورود'),
        ),
        migrations.AlterField(
            model_name='detailroom',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='is_Reservation',
            field=models.BooleanField(default=False, null=True, verbose_name='رزرو شده/ نشده'),
        ),
    ]
