# Generated by Django 4.1.5 on 2023-01-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0025_alter_detailroom_date_in_alter_detailroom_date_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailroom',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='detailroom',
            name='date_out',
        ),
    ]
