# Generated by Django 4.1.5 on 2023-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='State',
            field=models.CharField(max_length=50, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='شهر'),
        ),
    ]
