# Generated by Django 4.1.5 on 2023-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_state_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('family', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('role', models.CharField(max_length=200, verbose_name='سمت')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='شماره همراه')),
            ],
            options={
                'verbose_name': 'کارکنان',
                'verbose_name_plural': 'کارکنان',
            },
        ),
    ]
