# Generated by Django 4.1.5 on 2023-01-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره همراه'),
        ),
    ]
